name: walter310
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.1
  - setuptools=58.0.4    
  - cmake
  - ffmpeg
  - numpy
  - scipy
  - matplotlib
  - tqdm
  - gitpython
  - imageio
  - imageio-ffmpeg
  - pillow
  - pandas
  - scikit-learn
  - pyqt
  - pip:
      - huggingface-hub==0.8.1
      - transformers==4.21.1
      - timm==0.6.7
      - moviepy==1.0.3
      - wandb==0.13.2
      - opencv-python==4.6.0.66
