name: walter_entreno
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.1       # ← evita incompatibilidad con gym 0.19.0
  - setuptools=58.0.4 # ← necesario para el setup antiguo
  - cmake
  - ffmpeg
  - numpy
  - scipy
  - matplotlib
  - tqdm
  - gitpython
  - imageio
  - imageio-ffmpeg
  - pillow
  - pandas
  - scikit-learn
  - pyqt
  - pip:
      - allenact==0.5.1
      - allenact-plugins==0.5.1
      - huggingface-hub==0.8.1
      - transformers==4.21.1
      - timm==0.6.7
      - moviepy==1.0.3
      - wandb==0.13.2
      - gym==0.19.0
      - gym-notices==0.0.8
      - gym-minigrid==1.0.3
      - opencv-python==4.6.0.66
